### ISSUE TITLE
Flux-Instance Kustomize patches in Helm values not applied to resources

### ISSUE THREAD

**Issue by ghost** [controlplaneio-fluxcd/charts#68]
Firstly, thank you for your work, I live and love in Flux.

Potentially a bit of a niche problem here, but I'm getting stuck and running out of ideas. 
Here's a TL;DR:
What appears to be valid Helm values don't apply Kustomize patches to the patched objects.

Setup:
I'm deploying EKS and bootstrapping Flux-Operator and Flux-Instance with Terraform (OpenTofu really). The previous iteration of my clusters had me adding `patches` to the `clusters/<name>/flux-system/kustomization.yaml`, e.g.:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - target:
      kind: ServiceAccount
      name: source-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::<aws>:role/eks-irsa-flux-source-controller
```

Now, I'd love to deploy the FluxInstance properly first time with the Terraform, so, using Terraform, I deploy:
- a namespace
- a secret with the auth for the Github App
- a `helm_release` for Flux-Operator
- a `helm_release` for Flux-Instance (both these are pulled from the GHCR repo you kindly provide)

In HCL this looks like:
```
resource "helm_release" "flux_instance" {
 
  depends_on = [helm_release.flux_operator]

  name       = "flux-instance"
  namespace  = kubernetes_namespace_v1.flux-system.metadata.0.name
  repository = "oci://ghcr.io/controlplaneio-fluxcd/charts"
  chart      = "flux-instance"
  version    = var.flux_operator_version
  wait       = true

  values = [<<EOF
instance:
  components:
    - helm-controller
    - image-automation-controller
    - image-reflector-controller
    - kustomize-controller
    - notification-controller
    - source-controller
  distribution:
    registry: <AWS pull through registry>
  kustomize:
    patches:
      - target:
          kind: ServiceAccount
          name: source-controller
          namespace: flux-system
        patch: |
          - op: add
            path: /metadata/annotations
            value:
              eks.amazonaws.com/role-arn: arn:aws:iam::${var.aws_account}:role/eks-irsa-flux-source-controller
  EOF
  ]

  // Configure Flux Git sync.
  set {
    name  = "instance.sync.kind"
    value = "GitRepository"
  }
  set {
    name  = "instance.sync.url"
    value = "https://github.com/org/repo"
  }
  set {
    name  = "instance.sync.path"
    value = "clusters/${var.eks_cluster_name}"
  }
  set {
    name  = "instance.sync.ref"
    value = "refs/heads/${var.git_branch}"
  }
  set {
    name  = "instance.sync.provider"
    value = "github"
  }
  set {
    name  = "instance.sync.pullSecret"
    value = "github-app"
  }
}
```
Here's what that looks like once applied in Helm:
```
❯ helm get values flux-instance 
USER-SUPPLIED VALUES:
instance:
  components:
  - helm-controller
  - image-automation-controller
  - image-reflector-controller
  - kustomize-controller
  - notification-controller
  - source-controller
  distribution:
    registry: <aws ecr>/ghcr/fluxcd
  kustomize:
    patches:
    - patch: |
        - op: add
          path: /metadata/annotations
          value:
            eks.amazonaws.com/role-arn: arn:aws:iam::<aws account>:role/eks-irsa-flux-source-controller
      target:
        kind: ServiceAccount
        name: source-controller
        namespace: flux-system
  sync:
    kind: GitRepository
    path: clusters/<cluster name>
    provider: github
    pullSecret: github-app
    ref: refs/heads/sandbox
    url: https://github.com/org/repo
```

# The problem
The Kustomize patch values in the heredoc don't get applied.
I do get everything else specified in the heredoc, the `sync` block comes through fine, as does pulling from the AWS cache repo.
However...
```
❯ k get sa source-controller -o yaml | yq .metadata.annotations
kustomize.toolkit.fluxcd.io/ssa: Ignore
```

I've tried a few things, like quoting or unquoting the role, or using | or |- in the patches block, deleting and reapplying, etc etc. I also tried exporting the Helm values that were applied by the Terraform helm_release, templating fresh from the chart, and then applying it directly, and that still didn't do anything.
It's odd mostly because it's being defined in the way I'd expect it to be defined but still not coming through to the resources.

I'd rather not apply a cut down version of the FluxInstance using Helm, disregard it from the lifecycle in Terraform, and then let Flux take over and reconcile over the top of it, but if there is anything you know of, that would be fantastic 🙌
